# Pandas All in One

In [132]:
import pandas as pd

In [133]:
pd.__version__

'2.3.3'

In [134]:
#Pandas works on dataframes. Dataframes are structured rows and column or in simple words - tables.

# 1) Create Dataframe

In [135]:
df = pd.DataFrame([11,22,33])
print(df)

    0
0  11
1  22
2  33

In [136]:
df = pd.DataFrame([11,22,33], columns=["col_name"])         #assigning column name
print(df)

   col_name
0        11
1        22
2        33

In [137]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [138]:
data = {
    "Name" : ["Cobi", "Bhaswati", "Neha", "Reeva"],
    "Age" : [37, 26, 25, 22],
    "Salary" : [90000, 80000, 50000, 20000]
}
df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age  Salary
0      Cobi   37   90000
1  Bhaswati   26   80000
2      Neha   25   50000
3     Reeva   22   20000
<class 'pandas.core.frame.DataFrame'>

# 2) Basic DataFrame Understanding

In [139]:
#(shift + tab) gives the functions' details of the selected function

In [140]:
df.head(2)                      #gives top two rows from the DataFrame

       Name  Age  Salary
0      Cobi   37   90000
1  Bhaswati   26   80000

In [141]:
df.tail(2)                     #gives last 2 rows from the DataFrame

    Name  Age  Salary
2   Neha   25   50000
3  Reeva   22   20000

In [142]:
df.shape                    #gives rows and columns count - shape - (row, column)

(4, 3)

In [143]:
df.columns                 #gives name of the columns in list format with data type

Index(['Name', 'Age', 'Salary'], dtype='object')

In [144]:
df.rename(columns = {"Salary" : "Monthly_Salary"})  

#rename changes the column name but this method doesn't change the Dataframe as inplace function is False by the fault.

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000
2      Neha   25           50000
3     Reeva   22           20000

In [145]:
df                   #column name didn't change as we didn't store the change in a variable or change the inplace function.

       Name  Age  Salary
0      Cobi   37   90000
1  Bhaswati   26   80000
2      Neha   25   50000
3     Reeva   22   20000

In [146]:
df.rename(columns = {"Salary" : "Monthly_Salary"}, inplace = True)
df                                  #inplace = True says - change the column name in this DataFrame itself

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000
2      Neha   25           50000
3     Reeva   22           20000

In [147]:
df.info                            #gives the normal information of the DataFrame

<bound method DataFrame.info of        Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000
2      Neha   25           50000
3     Reeva   22           20000>

In [148]:
df.describe()                      #gives statistical summary of the DataFrame - mean, std, max, count etc

             Age  Monthly_Salary
count   4.000000        4.000000
mean   27.500000    60000.000000
std     6.557439    31622.776602
min    22.000000    20000.000000
25%    24.250000    42500.000000
50%    25.500000    65000.000000
75%    28.750000    82500.000000
max    37.000000    90000.000000

# 3) Save & Load Data from CSV

In [52]:
#format is = df_dataframe name.to_csv, we're writing "df.to_csv" because our DataFrame name is "df".
#saving/exporting the Dataframe in CSV format using to_csv
#this gives index values also

df.to_csv("Test_data.csv")

In [53]:
#saving the DataFrame without index values

df.to_csv("Test_data.csv", index = False)

In [51]:
load_df = pd.read_csv("Test_data.csv")             #loading the csv file in pandas
print(load_df)

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000
2      Neha   25           50000
3     Reeva   22           20000

# 4) Rows & Columns - Selection

In [55]:
#select column

df[["Name"]]           #gives single column

       Name
0      Cobi
1  Bhaswati
2      Neha
3     Reeva

In [149]:
df[["Name", "Monthly_Salary"]]            #gives multiple columns

       Name  Monthly_Salary
0      Cobi           90000
1  Bhaswati           80000
2      Neha           50000
3     Reeva           20000

In [62]:
#select rows
#loc - label based index

df.loc[df.Name== "Bhaswati"]              #gives the complete row of the given name

       Name  Age  Monthly_Salary
1  Bhaswati   26           80000

In [61]:
df.loc[(df.Name== "Cobi") & (df.Monthly_Salary> 50000)]      #gives the row for mentioned name and salary condition

   Name  Age  Monthly_Salary
0  Cobi   37           90000

In [67]:
df.loc[0:2]                   #loc doesn't follow basic indexing rule- [0:2] means starts from 0 to 2, include 2nd index's value also.

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000
2      Neha   25           50000

In [68]:
#iloc - index-value based
#iloc follows basic indexing rule- [0:2] means starts from 0th index goes to 1st index, excludes 2nd index

df.iloc[0]                 #gives all the column values associated with index 0 element

Name               Cobi
Age                  37
Monthly_Salary    90000
Name: 0, dtype: object

In [69]:
df.iloc[0:2]                     #gives values of multiple indexes

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000

# 5) Filter DataFrame

In [70]:
df

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000
2      Neha   25           50000
3     Reeva   22           20000

In [72]:
df["Age"] > 25                    #gives the records in boolean value where age> 25

0     True
1     True
2    False
3    False
Name: Age, dtype: bool

In [76]:
df[df["Age"] > 25]                #this gives the result in DataFrame

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000

In [77]:
df_age_filter = df[df["Age"] > 25]          
print(df_age_filter)

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000

In [80]:
df[(df["Age"] > 25) & (df["Monthly_Salary"] > 80000)]          #giving multiple conditions using '&' operator

   Name  Age  Monthly_Salary
0  Cobi   37           90000

In [150]:
#where is used to filter data without changing the table structure.
#for the data that doesn't fulfill the given condition shows as NaN in the table.

df.where(df["Age"] > 25)

       Name   Age  Monthly_Salary
0      Cobi  37.0         90000.0
1  Bhaswati  26.0         80000.0
2       NaN   NaN             NaN
3       NaN   NaN             NaN

In [84]:
df.where(df["Age"] > 25, other = "not eligible")          #prints the NaN values as not eligible

           Name           Age Monthly_Salary
0          Cobi            37          90000
1      Bhaswati            26          80000
2  not eligible  not eligible   not eligible
3  not eligible  not eligible   not eligible

# 6) Rows & Column - Operations(Add, Update, Delete)

In [85]:
print(df)

       Name  Age  Monthly_Salary
0      Cobi   37           90000
1  Bhaswati   26           80000
2      Neha   25           50000
3     Reeva   22           20000

In [220]:
#add new column

df["Team"] = ["CEO", "CTO", "DA", "HR"]
print(df)

       Name  Age  Monthly_Salary Team
0      Cobi   37           90000  CEO
1  Bhaswati   26           80000  CTO
2      Neha   25           50000   DA
3     Reeva   22           20000   HR

In [221]:
df['Bonus'] = df['Monthly_Salary'] * 0.20
print(df)

       Name  Age  Monthly_Salary Team    Bonus
0      Cobi   37           90000  CEO  18000.0
1  Bhaswati   26           80000  CTO  16000.0
2      Neha   25           50000   DA  10000.0
3     Reeva   22           20000   HR   4000.0

In [222]:
#add new row

df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 20000]            
df

       Name  Age  Monthly_Salary Team    Bonus
0      Cobi   37           90000  CEO  18000.0
1  Bhaswati   26           80000  CTO  16000.0
2      Neha   25           50000   DA  10000.0
3     Reeva   22           20000   HR   4000.0
4       ABC   21           21000   IT  20000.0

In [223]:
print(len(df))

5

In [224]:
#update value

df.loc[0, 'Monthly_Salary'] = 95000            #updated 0th index's salary to 95000
print(df)

       Name  Age  Monthly_Salary Team    Bonus
0      Cobi   37           95000  CEO  18000.0
1  Bhaswati   26           80000  CTO  16000.0
2      Neha   25           50000   DA  10000.0
3     Reeva   22           20000   HR   4000.0
4       ABC   21           21000   IT  20000.0

In [225]:
#update value using column value

df.loc[df.Name == 'Cobi' , 'Monthly_Salary'] = 90000
print(df)

       Name  Age  Monthly_Salary Team    Bonus
0      Cobi   37           90000  CEO  18000.0
1  Bhaswati   26           80000  CTO  16000.0
2      Neha   25           50000   DA  10000.0
3     Reeva   22           20000   HR   4000.0
4       ABC   21           21000   IT  20000.0

In [226]:
#delete value - row & column values
#by the fault axis is 0 while deleting either rows or columns so while deleting columns we need to mention axis = 1.

df = df.drop(df[df.Name == 'ABC'].index)           #deleting ABC row, axis= 0(axis 0 means rows, axis-1 means columns)
print(df)

       Name  Age  Monthly_Salary Team    Bonus
0      Cobi   37           90000  CEO  18000.0
1  Bhaswati   26           80000  CTO  16000.0
2      Neha   25           50000   DA  10000.0
3     Reeva   22           20000   HR   4000.0

In [234]:
#deleting row using index value

df.drop(1, axis = 0)          #deleting row without inplace or making new df, but using index num

    Name  Age  Monthly_Salary Team
0   Cobi   37           90000  CEO
2   Neha   25           50000   DA
3  Reeva   22           20000   HR

In [227]:
#drop column(axis = 1)

df.drop('Bonus' , axis= 1, inplace=True)              #inplace helps to drop the row/column in one go
print(df)

       Name  Age  Monthly_Salary Team
0      Cobi   37           90000  CEO
1  Bhaswati   26           80000  CTO
2      Neha   25           50000   DA
3     Reeva   22           20000   HR

In [229]:
#delete multiple columns

df.drop(['Age', 'Team'] , axis = 1)

       Name  Monthly_Salary
0      Cobi           90000
1  Bhaswati           80000
2      Neha           50000
3     Reeva           20000

In [239]:
print(df)                                    #returns age & team column as inplace is False by the fault

       Name  Age  Salary Team
0      Cobi   37   90000  CEO
1  Bhaswati   26   80000  CTO
2      Neha   25   50000   DA
3     Reeva   22   20000   HR

In [240]:
#sort values - ascending or descending
#by the fault ascending

df.rename(columns ={'Monthly_Salary' : 'Salary'} , inplace = True)
df.sort_values('Salary')                           #sorted table by salary ascending order

       Name  Age  Salary Team
3     Reeva   22   20000   HR
2      Neha   25   50000   DA
1  Bhaswati   26   80000  CTO
0      Cobi   37   90000  CEO

In [241]:
df.sort_values('Salary', ascending = False)           #sorted salary descending order

       Name  Age  Salary Team
0      Cobi   37   90000  CEO
1  Bhaswati   26   80000  CTO
2      Neha   25   50000   DA
3     Reeva   22   20000   HR

# 7) Working with Date Values

In [242]:
df['DOJ'] = ['2026-01-01', '2026-01-15', '2026-01-25', '2026-02-10']
print(df)

       Name  Age  Salary Team         DOJ
0      Cobi   37   90000  CEO  2026-01-01
1  Bhaswati   26   80000  CTO  2026-01-15
2      Neha   25   50000   DA  2026-01-25
3     Reeva   22   20000   HR  2026-02-10

In [248]:
df['DOJ'].dtype                #'O' means object- not considering DOJ as date time format

dtype('<M8[ns]')

In [249]:
df['DOJ'] = pd.to_datetime(df['DOJ'])                #updating DOJ to date-time format
df['DOJ'].dtype

dtype('<M8[ns]')

In [250]:
df1 = df
print(df1)

       Name  Age  Salary Team        DOJ
0      Cobi   37   90000  CEO 2026-01-01
1  Bhaswati   26   80000  CTO 2026-01-15
2      Neha   25   50000   DA 2026-01-25
3     Reeva   22   20000   HR 2026-02-10

In [252]:
df1['DOJ2'] = ['01-01-2026', '15-01-2026', '25-01-2026', '10-02-2026']
print(df1)
df1['DOJ2'].dtype

       Name  Age  Salary Team        DOJ        DOJ2
0      Cobi   37   90000  CEO 2026-01-01  01-01-2026
1  Bhaswati   26   80000  CTO 2026-01-15  15-01-2026
2      Neha   25   50000   DA 2026-01-25  25-01-2026
3     Reeva   22   20000   HR 2026-02-10  10-02-2026

dtype('O')

In [254]:
#df1['DOJ2'] = pd.to_datetime(df1['DOJ2'])            

#this block of code will show error as DOJ2 isn't in datetime format

In [260]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format = '%d-%m-%Y')

In [261]:
print(df1)
df1['DOJ2'].dtype

       Name  Age  Salary Team        DOJ       DOJ2
0      Cobi   37   90000  CEO 2026-01-01 2026-01-01
1  Bhaswati   26   80000  CTO 2026-01-15 2026-01-15
2      Neha   25   50000   DA 2026-01-25 2026-01-25
3     Reeva   22   20000   HR 2026-02-10 2026-02-10

dtype('<M8[ns]')

In [265]:
df = df.drop('DOJ2', axis = 1)
print(df)

       Name  Age  Salary Team        DOJ
0      Cobi   37   90000  CEO 2026-01-01
1  Bhaswati   26   80000  CTO 2026-01-15
2      Neha   25   50000   DA 2026-01-25
3     Reeva   22   20000   HR 2026-02-10

In [ ]:
# Extract year, month, day

In [273]:
df['DOJ'].dt.year                    #gives year from the data

0    2026
1    2026
2    2026
3    2026
Name: DOJ, dtype: int32

In [274]:
df['DOJ'].dt.month                   #gives month

0    1
1    1
2    1
3    2
Name: DOJ, dtype: int32

In [275]:
df['DOJ'].dt.day                      #gives day

0     1
1    15
2    25
3    10
Name: DOJ, dtype: int32

In [276]:
df['DOJ'].dt.day_name()                 #gives day name

0    Thursday
1    Thursday
2      Sunday
3     Tuesday
Name: DOJ, dtype: object

In [279]:
df['Month'] = df['DOJ'].dt.month               #directly extract one element of date 
print(df)

       Name  Age  Salary Team        DOJ  Month
0      Cobi   37   90000  CEO 2026-01-01      1
1  Bhaswati   26   80000  CTO 2026-01-15      1
2      Neha   25   50000   DA 2026-01-25      1
3     Reeva   22   20000   HR 2026-02-10      2

In [280]:
df['DOJ'] + pd.Timedelta(days= 90)

0   2026-04-01
1   2026-04-15
2   2026-04-25
3   2026-05-11
Name: DOJ, dtype: datetime64[ns]

# 8) Handling Missing Values

In [282]:
print(df)

       Name  Age  Salary Team        DOJ  Month
0      Cobi   37   90000  CEO 2026-01-01      1
1  Bhaswati   26   80000  CTO 2026-01-15      1
2      Neha   25   50000   DA 2026-01-25      1
3     Reeva   22   20000   HR 2026-02-10      2

In [283]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [284]:
import numpy as np

In [286]:
df.loc[df.Name == 'Cobi', 'Salary'] = np.nan
print(df)

       Name  Age   Salary Team        DOJ  Month
0      Cobi   37      NaN  CEO 2026-01-01      1
1  Bhaswati   26  80000.0  CTO 2026-01-15      1
2      Neha   25  50000.0   DA 2026-01-25      1
3     Reeva   22  20000.0   HR 2026-02-10      2

In [287]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False    True  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [291]:
df.isnull().sum()                     #shows the position of the null values

Name      0
Age       0
Salary    1
Team      0
DOJ       0
Month     0
dtype: int64

In [293]:
df.fillna(0)                        #assigning 0 to the null value

       Name  Age   Salary Team        DOJ  Month
0      Cobi   37      0.0  CEO 2026-01-01      1
1  Bhaswati   26  80000.0  CTO 2026-01-15      1
2      Neha   25  50000.0   DA 2026-01-25      1
3     Reeva   22  20000.0   HR 2026-02-10      2

In [294]:
print(df)

       Name  Age   Salary Team        DOJ  Month
0      Cobi   37      NaN  CEO 2026-01-01      1
1  Bhaswati   26  80000.0  CTO 2026-01-15      1
2      Neha   25  50000.0   DA 2026-01-25      1
3     Reeva   22  20000.0   HR 2026-02-10      2

# 9) Aggregation & Group By

In [298]:
df['Month'].value_counts()                  #.value_count() gives frequency of values

Month
1    3
2    1
Name: count, dtype: int64

In [299]:
df[df['Month']==1].value_counts()                #counts the values in Jan month, 1,2,3.. - Jan, Feb, March etc..

Name      Age  Salary   Team  DOJ         Month
Bhaswati  26   80000.0  CTO   2026-01-15  1        1
Neha      25   50000.0  DA    2026-01-25  1        1
Name: count, dtype: int64

In [305]:
#aggregation based on group by

df.groupby('Month')['Salary'].sum()                 #returns total salary in every month

Month
1    130000.0
2     20000.0
Name: Salary, dtype: float64

In [304]:
df.groupby('Month')['Salary'].mean()                 #returns average salary in every month

Month
1    65000.0
2    20000.0
Name: Salary, dtype: float64

In [307]:
df.groupby('Month').agg({'Salary' : 'mean', 'Name' : 'count'})          #65k is avg salary of 3 people, 20k is avg of 1 person

        Salary  Name
Month
1      65000.0     3
2      20000.0     1

# 10) Concatenate & Merge DataFrame(JOINS)

In [308]:
df1 = pd.DataFrame({'ID' : [1,2,3], 'Name' : ['A','B','C']})
print(df1)

   ID Name
0   1    A
1   2    B
2   3    C

In [309]:
df2 = pd.DataFrame({'ID' : [1,2,2,4], 'Score' : [88,96,77,79]})
print(df2)

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [313]:
pd.concat([df1,df2], axis=0)           #vertically joining two tables/row level/top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [314]:
pd.concat([df1,df2], axis=1)                  #horizontally joining two tables/column level/side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [316]:
#merge = join

pd.merge(df1,df2, how='inner', on= 'ID')             #inner join

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [317]:
pd.merge(df1,df2, how='outer', on= 'ID')             #outer join

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN
4   4  NaN   79.0

In [318]:
pd.merge(df1,df2, how='left', on= 'ID')              #left join

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN

In [319]:
pd.merge(df1,df2, how='inner', left_on= 'ID', right_on= 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77